---
- name: Deploy LAMP stack on each server and single PHP page
  hosts: webservers
  gather_facts: true
  tasks:

    - name: install Apache 
      yum:
        name: httpd
        state: present

    - name: install MYSQL server
      yum:
        name: mysql-server
        state: present

    - name: install PHP
      yum: 
        name: 
         - php
         - php-mysqlnd
         - php-fpm
         - php-cli
         - php-json
        state: present

    - name: Ensure Apache is started and enabled 
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Restart Apache to load PHP
      service:
        name: httpd
        state: restarted

    - name: Ensure MYSQL is started and enabled
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Copy content to index.php
      copy:
        dest: /var/www/html/index.php
        content: |
          <?php
              echo "<p>Hello World</p>";
          ?>
    - name: Ensure firewall allows HTTP and MySQL traffic
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes      




