- name: Modify /etc/hosts file on each server
  hosts: all
  become: yes
  remote_user: root
  become_method: sudo
  become_user: root
  gather_facts: yes
  tasks:
    - name: Copy hosts file from template
      template:
        src: templates/hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
